CREATE TABLE `yourdbname`.`users` ( 
	`id` INT NOT NULL AUTO_INCREMENT , 
	`username` VARCHAR(30) NOT NULL , 
	`email` VARCHAR(30) NOT NULL , 
	`password` VARCHAR(255) NOT NULL , 
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)
	) ENGINE = InnoDB;